### ISSUE TITLE
KeyError when running decoil

### ISSUE THREAD

**Issue by eesiribloom** [madagiurgiu25/decoil-pre#17]
I have been trying to use decoil installed from source but I am experiencing an Error. Example command:

```
for SAMPLE in 1 2 3 4
do
mkdir -p ${SAMPLE}T/logs
mkdir -p ${SAMPLE}T/tmp

export BAM_INPUT="alignment/${SAMPLE}T_aligned.bam"
export OUTPUT_FOLDER="${SAMPLE}T"
export NAME="${SAMPLE}T"
export GENOME="resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
export ANNO="anno.gtf"

decoil-pipeline sv-reconstruct \
--bam ${BAM_INPUT} \
--outputdir ${OUTPUT_FOLDER} \
--name ${NAME} \
--reference-genome ${GENOME} \
--annotation-gtf ${ANNO} \
--fragment-min-cov 40 \
--min-cov 40 \
--min-cov-alt 20 \
--min-vaf 0.01 \
--filter-score 40 \
--fragment-min-size 1000 \
--min-sv-len 5000
done
```

example error output:
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
[Thu Sep  5 02:40:49 2024]
Error in rule decoil:
    jobid: 0
    input: 2T/sv.sniffles.vcf, 2T/coverage.bw, alignment/2T_aligned.bam, alignment/2T_aligned.bam.bai
    output: 2T/summary.txt, 2T/reconstruct.bed, 2T/reconstruct.links.txt, 2T/reconstruct.fasta, 2T/reconstruct.ecDNA.bed, 2T/reconstruct.links.ecDNA.txt, 2T/reconstruct.ecDNA.fasta, 2T/reconstruct.ecDNA.filtered.bed, 2T/reconstruct.links.ecDNA.filtered.txt, 2T/reconstruct.ecDNA.filtered.fasta
    log: 2T/logs/logs_decoil (check log file(s) for error details)

RuleException:
KeyError in file /exports/igmm/eddie/semple-lab/eesiribloom/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/rules/decoil.smk, line 21:
None
  File "/exports/igmm/eddie/semple-lab/eesiribloom/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/cli/rules/decoil.smk", line 21, in __rule_decoil
  File "/exports/igmm/eddie/semple-lab/eesiribloom/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/main.py", line 205, in run_reconstruction
  File "/exports/igmm/eddie/semple-lab/eesiribloom/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/encode/operations.py", line 231, in remove_duplicated_edges
  File "/exports/igmm/eddie/semple-lab/eesiribloom/conda/envs/envdecoil/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-04T163315.016598.snakemake.log
Traceback (most recent call last):
  File "/exports/igmm/eddie/semple-lab/eesiribloom/conda/envs/envdecoil/lib/python3.8/site-packages/decoil-1.1.3a0-py3.8.egg/decoil/command.py", line 170, in entry_point
    raise Exception("Snakemake failed")
Exception: Snakemake failed
```

**Comment by madagiurgiu25** [comment]
Dear @eesiribloom,

Please use full paths over relative paths. 

```
export BAM_INPUT="$PWD/alignment/${SAMPLE}T_aligned.bam"
export OUTPUT_FOLDER="$PWD/${SAMPLE}T"
export NAME="${SAMPLE}T"
export GENOME="$PWD/resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
export ANNO="$PWD/anno.gtf"
```


Does the error still persist?

**Comment by eesiribloom** [comment]
Apologies, In the original script I am using full paths and I am still seeing the same error. 
version `Decoil 1.1.3-alpha`

**Comment by madagiurgiu25** [comment]
Hi!

So I have done a pip release -> https://github.com/madagiurgiu25/decoil-pre/tree/main?tab=readme-ov-file#getting-started-using-conda-and-pip

Maybe you want to check that out. I do not recommend installing decoil from source, in particular if the tag is "-alpha" or "-beta" because that is for sure an unsable version.

**Comment by eesiribloom** [comment]
I have tried with the pip install on the latest version but still see the same error. 

It's only on particular (seemingly random) samples which makes it hard to understand where the issue is coming from. 

I have tried running with `--debug` but not change in output. 

Is it an issue with the coverage file?

**Comment by MJoseMo** [comment]
Dear @madagiurgiu25, I aligned the reads using ngmlr and tried to reconstruct ecDNAs with decoil. However, I encountered an error and I don't know why. I've trimmed the log file to make it more legible. The last files created are: 
-  reconstruct.bed_debug
- reconstruct.links.txt_debug
- fragments_initial.bed
- fragments_clean_1-3.bed
version: Decoil 1.1.2

`Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job          count
---------  -------
all              1
coverage         1
decoil           1
survivor         1
svcalling        1
total            5

Select jobs to execute...

[Wed Dec  4 12:02:40 2024]
rule svcalling:
    input: ex_ngmlr_sorted.bam
    output: ex_ngmlr_dec/sv.sniffles.vcf
    log: ex_ngmlr_dec/logs/logs_sniffles
    jobid: 1
    reason: Forced execution
    wildcards: dirname=ex_ngmlr_dec
    resources: tmpdir=/junk/tmpYwIO


            sniffles -t 4 -m ex_ngmlr_sorted.bam             -v ex_ngmlr_dec/sv.sniffles.vcf --min_homo_af 0.7             --min_het_af 0.1 --min_length 50             --cluster --genotype --min_support 4 --report-seq &> ex_ngmlr_dec/logs/logs_sniffles
            
[Wed Dec  4 12:15:36 2024]
Finished job 1.
1 of 5 steps (20%) done
Select jobs to execute...

[Wed Dec  4 12:15:36 2024]
rule survivor:
    input: ex_ngmlr_dec/sv.sniffles.vcf
    output: ex_ngmlr_dec/sv.sniffles.bedpe
    log: ex_ngmlr_dec/logs/logs_survivor
    jobid: 2
    reason: Missing output files: ex_ngmlr_dec/sv.sniffles.bedpe; Input files updated by another job: ex_ngmlr_dec/sv.sniffles.vcf
    wildcards: dirname=ex_ngmlr_dec
    resources: tmpdir=/junk/tmpYwIO


        SURVIVOR vcftobed ex_ngmlr_dec/sv.sniffles.vcf -1 -1 ex_ngmlr_dec/sv.sniffles.bedpe &> ex_ngmlr_dec/logs/logs_survivor
        
[Wed Dec  4 12:15:36 2024]
Finished job 2.
2 of 5 steps (40%) done
Select jobs to execute...

[Wed Dec  4 12:15:36 2024]
rule coverage:
    input: ex_ngmlr_sorted.bam, ex_ngmlr_sorted.bam.bai
    output: ex_ngmlr_dec/coverage.bw
    log: ex_ngmlr_dec/logs/logs_cov
    jobid: 3
    reason: Forced execution
    wildcards: dirname=ex_ngmlr_dec
    resources: tmpdir=/junk/tmpYwIO


        bamCoverage --bam ex_ngmlr_sorted.bam -o ex_ngmlr_dec/coverage.bw --binSize 50 -p 4 &> ex_ngmlr_dec/logs/logs_cov
        
[Wed Dec  4 12:18:45 2024]
Finished job 3.
3 of 5 steps (60%) done
Select jobs to execute...

[Wed Dec  4 12:18:45 2024]
rule decoil:
    input: ex_ngmlr_dec/sv.sniffles.vcf, ex_ngmlr_dec/coverage.bw, ex_ngmlr_sorted.bam, ex_ngmlr_sorted.bam.bai
    output: ex_ngmlr_dec/summary.txt, ex_ngmlr_dec/reconstruct.bed, ex_ngmlr_dec/reconstruct.links.txt, ex_ngmlr_dec/reconstruct.fasta, ex_ngmlr_dec/reconstruct.ecDNA.bed, ex_ngmlr_dec/reconstruct.links.ecDNA.txt, ex_ngmlr_dec/reconstruct.ecDNA.fasta, ex_ngmlr_dec/reconstruct.ecDNA.filtered.bed, ex_ngmlr_dec/reconstruct.links.ecDNA.filtered.txt, ex_ngmlr_dec/reconstruct.ecDNA.filtered.fasta
    log: ex_ngmlr_dec/logs/logs_decoil
    jobid: 4
    reason: Missing output files: ex_ngmlr_dec/reconstruct.ecDNA.fasta, ex_ngmlr_dec/reconstruct.ecDNA.filtered.fasta, ex_ngmlr_dec/reconstruct.links.txt, ex_ngmlr_dec/reconstruct.bed, ex_ngmlr_dec/reconstruct.ecDNA.filtered.bed, ex_ngmlr_dec/reconstruct.fasta, ex_ngmlr_dec/reconstruct.ecDNA.bed, ex_ngmlr_dec/summary.txt, ex_ngmlr_dec/reconstruct.links.ecDNA.txt, ex_ngmlr_dec/reconstruct.links.ecDNA.filtered.txt; Input files updated by another job: ex_ngmlr_dec/coverage.bw, ex_ngmlr_dec/sv.sniffles.vcf
    wildcards: dirname=ex_ngmlr_dec
    resources: tmpdir=/junk/tmpYwIO

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
[Wed Dec  4 12:21:17 2024]
Error in rule decoil:
    jobid: 0
    input: ex_ngmlr_dec/sv.sniffles.vcf, ex_ngmlr_dec/coverage.bw, ex_ngmlr_sorted.bam, ex_ngmlr_sorted.bam.bai
    output: ex_ngmlr_dec/summary.txt, ex_ngmlr_dec/reconstruct.bed, ex_ngmlr_dec/reconstruct.links.txt, ex_ngmlr_dec/reconstruct.fasta, ex_ngmlr_dec/reconstruct.ecDNA.bed, ex_ngmlr_dec/reconstruct.links.ecDNA.txt, ex_ngmlr_dec/reconstruct.ecDNA.fasta, ex_ngmlr_dec/reconstruct.ecDNA.filtered.bed, ex_ngmlr_dec/reconstruct.links.ecDNA.filtered.txt, ex_ngmlr_dec/reconstruct.ecDNA.filtered.fasta
    log: ex_ngmlr_dec/logs/logs_decoil (check log file(s) for error details)

RuleException:
KeyError in file software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/cli/rules/decoil.smk, line 21:
4157
  File "software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/cli/rules/decoil.smk", line 21, in __rule_decoil
  File "software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/main.py", line 220, in run_reconstruction
  File "software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/search/quantify.py", line 453, in run_quantification
  File "software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/search/quantify.py", line 413, in compute_proportions
  File "software/conda/envs/decoil/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-12-04T120239.511671.snakemake.log
Traceback (most recent call last):
  File "software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/command.py", line 170, in entry_point
    raise Exception("Snakemake failed")
Exception: Snakemake failed

Set QUAL.MEAN_COVERAGE_WGS to  1.1557224607938812
Set QUAL.MINIMAL_FRAGMENT_COVERAGE to  5
2024-12-04 12:18:52,893 - reconstruct.encode - INFO - 0. Start processing 
2024-12-04 12:18:52,893 - reconstruct.encode - INFO - ex_ngmlr_dec/sv.sniffles.vcf
2024-12-04 12:18:52,893 - reconstruct.encode - INFO - 1. Get all breakpoints and parse SV information
Total number of entries in vcf 12419
SV kept for graph generation 1286
2024-12-04 12:18:54,928 - reconstruct.clean - INFO - Remove 11968776
2024-12-04 12:18:55,383 - reconstruct.encode - INFO - 1. 2. After cleaning breakpoints
2024-12-04 12:18:55,384 - reconstruct.encode - INFO - 2. Fragment the genome
2024-12-04 12:18:56,228 - reconstruct.encode - INFO - 3. Encode SV;s in graph
2024-12-04 12:18:56,288 - reconstruct.clean - INFO - 5. Add edges connecting neighboring fragments
2024-12-04 12:18:56,288 - reconstruct.clean - INFO - 5. Add edges connecting neighboring fragments
Spatial ->> Chr breakpoint count node_left node_right chr1 968781 44 3 6
Remove fragment due to size 21 chr1:1125793-1125909
remove edge  13432  connecting nodes u,v  111 130
Set QUAL.MAX_COVERAGE to  13660.859271523179
2024-12-04 12:20:51,580 - reconstruct.search - INFO - 6. Find path
2024-12-04 12:21:02,296 - reconstruct - INFO - 7. Convert simple circles (all) to bed
2024-12-04 12:21:02,321 - reconstruct - INFO - 8. Convert bed to links
2024-12-04 12:21:04,097 - reconstruct.search - INFO - 6. Combine simple circles
2024-12-04 12:21:06,852 - reconstruct.clean - INFO - 4. Compute likely circles
2024-12-04 12:21:06,852 - reconstruct.clean - INFO - 4. Compute likely circles
2024-12-04 12:21:06,853 - reconstruct.clean - INFO - 4.0 Filter out highly similar circles
2024-12-04 12:21:06,853 - reconstruct.clean - INFO - 4.0 Filter out highly similar circles
2024-12-04 12:21:06,853 - reconstruct.clean - INFO - 4.1. Build identity matrix
2024-12-04 12:21:06,853 - reconstruct.clean - INFO - 4.1. Build identity matrix
2024-12-04 12:21:07,916 - reconstruct.clean - INFO - 4.2 Find clusters
2024-12-04 12:21:07,916 - reconstruct.clean - INFO - 4.2 Find clusters
2024-12-04 12:21:16,335 - reconstruct.clean - INFO - 4.3. Quantify circles
2024-12-04 12:21:16,335 - reconstruct.clean - INFO - 4.3. Quantify circles
[0.57820073 0.42179927]
[0.41038179 0.58961821]
Perform lasso regression
       5    6  wgs_circle
77   1.0  1.0         1.0
85   1.0  2.0         1.0
wgs  0.0  0.0         1.0
[77.7125, 111.65384615384616, 1.1557224607938812]
[41.72766117 34.23523126  0.        ]
[41.72766117 34.23523126]
after filtering
[41.72766117 34.23523126]
[0.53544346 0.46455654]
[0.47895602 0.52104398]
Perform lasso regression
      359  373  374  375  wgs_circle
4005  0.0  1.0  1.0  1.0         1.0
4009  0.0  2.0  2.0  2.0         1.0
4017  1.0  2.0  2.0  1.0         1.0
4021  1.0  1.0  1.0  0.0         1.0
wgs   0.0  0.0  0.0  0.0         1.0
[55.11742424242424, 20.759367291805333, 96.01139896373057, 74.71516079632465, 1.1557224607938812]
[5.32690286e+01 1.20006471e+01 2.53765263e-15 0.00000000e+00
 0.00000000e+00]
[5.32690286e+01 1.20006471e+01 2.53765263e-15 0.00000000e+00]
after filtering
[53.26902857 12.00064711]
[-0.]
[1.]
Perform lasso regression
[4157]
--------
details!
	snakefile: software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/cli/Snakefile
	workflowfile: software/conda/envs/decoil/lib/python3.8/site-packages/decoil-1.1.2-py3.8.egg/decoil/cli/sv-reconstruct.json
	params: {'bam': 'ex_ngmlr_sorted.bam', 'outputdir': 'ex_ngmlr_dec', 'reference_genome': 'reference/GRCh38.p13.genome_filtered.fa', 'annotation_gtf': 'reference/gencode.v38.annotation.sorted.gtf', 'name': 'ex_ngmlr_dec', 'threads': 4, 'svcaller': 'sniffles', 'workflow': 'sv-reconstruct', 'container': False, 'decoil': '1.1.2'}
	target: all
--------
-------
Status: Failed
User time (seconds): 1118.26
#######

`
Any insights on this issue would be greatly appreciated, Thanks :)

**Comment by madagiurgiu25** [comment]
Hi @eesiribloom,

could you try installing decoil from source with the latest version and see if it is still failing for your sample.
I did a couple of bug fixes. Thank you.
Best,
Madalina

**Comment by madagiurgiu25** [comment]
@eesiribloom, I will close the issue due to inactivity, please let me know if this still persist with the latest commit.
